# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Backend Continuous Integration
on:
  push:
    branches: [ main ]
    paths:
      - 'wedding-api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'wedding-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run test
      run: mvn --batch-mode --update-snapshots verify
      working-directory: ./wedding-api

  package:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Copy configuration file for production
        uses: prewk/s3-cp-action@v2
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: ${{ secrets.BUCKET_FOLDER_PATH }}/application-prod.properties
          dest: ./wedding-api/src/main/resources

      - name: Copy Firebase configuratioon file
        uses: prewk/s3-cp-action@v2
        with:
          aws_region: ${{ secrets.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: ${{ secrets.BUCKET_FOLDER_PATH }}/ursuleric-firebase-adminsdk-hekt3-b31e0d3197.json
          dest: ./wedding-api/src/main/resources/fcm

      - name: Package application for production
        run: mvn clean install -DskipTests -Pprod
        working-directory: wedding-api

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Dashboard to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./wedding-api
          file: ./wedding-api/Dockerfile.prod
          push: true
          tags: tericcabrel/wedding-api:latest

